---
dist: trusty
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
  - 2.5.1
env:
  global:
    - BEAKER_PUPPET_COLLECTION=puppet6 PUPPET_GEM_VERSION="~> 6.0"
matrix:
  fast_finish: true
  include:
    -
      bundler_args: 
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=docker/centos-7 BEAKER_TESTMODE=apply
      rvm: 2.5.1
      script: bundle exec rake beaker
      services: docker
      sudo: required
    -
      bundler_args: 
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=docker/ubuntu-14.04 BEAKER_TESTMODE=apply
      rvm: 2.5.1
      script: bundle exec rake beaker
      services: docker
      sudo: required
    -
      env: CHECK="syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop"
    -
      env: CHECK=parallel_spec
    -
      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec
      rvm: 2.4.4
branches:
  only:
    - master
    - /^v\d/
    - release
notifications:
  email: false
  slack:
    secure: YeM6B8pYLnVloiKkwtKx3RtqmXJbRlOAeMbVP47aeFC2fzp+8G79Nug0UjOdfx+QeU4uOSLk15pbk3k3fbaAwiH81Yo6FYChgEO8I/tls6+onZdGMwTlE10XEXuVhq1CYo4ITYOoCbzhtkEM5ptdPzooNdC7mUCsNh5bvX5gOaefIsaPqpcfnHZ/DdgnGrnK+urJpnCjKyyNKasPwOtAsj/wCPMd0dAXV8zmdGjI7suJXoGE9+SSvY+mWrumk4eIYaZxa/Nij3W1eMG9zpsrqSIxUoWYPm9ctXpQXrnOWNS4Ig/gIfdHKW5xWgYkzqKy//YU5rBZzyc/JYIwKXGLKZyl7ba7tBD2oEUgM/2l1d6E4PIlUugmes9ODZtt4ttpKJXflXxpBtdFuTDZyaU9jWwnySjPpuXNNkpnvr6t9ADkfQQ48gOlDVZVKrcwHdV8A6N8P29e9TTrP8ztYIZYO+Rxe4L0nuIEtlZhM6QTcLh02zzf5Q7qtL/ks7w3bI37OknqcVxi55dHFXOGFLELbkAuLS8h+ze+53grxViyBTBaaHp2nCW6xP3F9YXZ4mpSBlsbhJhPBYZZw48mkhQqlkgmiUskX70/+ON46wBCeJZPhZSnHyximPS/5dfVJsVlLJy/2LXz6ytN31Nrv+N/NiQCK1Tvy+msMBZj5/T4G/o=
deploy:
  provider: puppetforge
  user: puppet
  password:
    secure: ""
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
